### ISSUE TITLE
Show Shipping method validation error to customer

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-nextjs-demo-store#114]
If a shipping method is not selected at the checkout the customer should be made aware of what they need to do to complete the checkout. 

Proposed solutions:
- Notification bar stating "Please select a shipping method to complete your order"
- Highlight the Shipping Method field in red

**Comment by pierrolabo** [comment]
Hi everyone,
I'm poking around for fun ...
i'm able to highlight the shipping method field if nothing is selected when we press the checkout button but unfortunately the API doesn't return me available shipping options for any countries ( https://api.chec.io/v1/checkouts/chkt_75v7GqzbkLREXl/helper/shipping_options?country=CN )

**Comment by JoelJJoseph** [comment]
The method of shipping is not selected at the checkout.

The notification bar should be select shipping order to complete the order. 
Highlight the Shipping Method field

**Comment by jaepass** [comment]
Currently 84 countries are included arbitrarily in the one shipping zone for this demo account. The reason why the shipping options aren't showing in the dropdown is because not all countries were included. We have several checkout shipping helpers that can help with populating only the countries that are included for the checkout token and that particular checkout helper is not being used for this checkout form. I see two fixes for improving the checkout form:
- Show some form of alert message when shipping method is not selected before pressing checkout
- Change fetch shipping methods to only fetch countries included in the demo account https://commercejs.com/docs/sdk/checkout#list-available-shipping-countries (I will raise another issue for enhancing this)

**Comment by robbieaverill** [comment]
You could also disable the checkout button until the shipping method has been selected

**Comment by drobiu** [comment]
Hey, can I try tackling that issue?

**Comment by jaepass** [comment]
yes definitely go for it thanks!

**Comment by tacoelho** [comment]
As no one was assigned I made a PR.

**Comment by Abhi947223** [comment]
I have gone through  documentation/readme but not able to run the localserver on my machine

**Comment by asha15** [comment]
Can i know does this issue was solved?

**Comment by ScopeyNZ** [comment]
The issue is still open, but there's a PR to fix it that's in review right now (#118)

**Comment by SHROYETA20** [comment]
You could also disable the checkout button until the shipping method has been selected.

**Comment by ShraddhaGeek** [comment]
Can I take if this is still open?

**Comment by jaepass** [comment]
The issue is free for anyone to pick up! Just submit a pr for it for review!

**Comment by drobiu** [comment]
I've created a pr for this issue
